export const ERROR_CODES = {
  // Goal & Milestone
  GOAL_NOT_FOUND: 'ERR_GOAL_NOT_FOUND',
  MILESTONE_NOT_FOUND: 'ERR_MILESTONE_NOT_FOUND',
  INVALID_TRANSITION: 'ERR_INVALID_TRANSITION',
  ALREADY_COMPLETED: 'ERR_ALREADY_COMPLETED',
  ALREADY_SCHEDULED: 'ERR_ALREADY_SCHEDULED',

  // Planner
  PLANNER_NOT_FOUND: 'ERR_PLANNER_NOT_FOUND',
  INVALID_RECURRENCE: 'ERR_INVALID_RECURRENCE',

  // Task & Focus
  TASK_NOT_FOUND: 'ERR_TASK_NOT_FOUND',
  FOCUS_SESSION_NOT_FOUND: 'ERR_FOCUS_SESSION_NOT_FOUND',

  // Auth & Permissions
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',

  // General & System
  NOT_FOUND: 'ERR_NOT_FOUND',
  VALIDATION: 'ERR_VALIDATION',
  CONFLICT: 'ERR_CONFLICT',
  BAD_REQUEST: 'ERR_BAD_REQUEST',
  INTERNAL_SERVER: 'ERR_INTERNAL_SERVER'
};
